### PR TITLE
A lot of errors when running `hatch run train`

### PR DESCRIPTION
**Pull request by botbw**
Hi, I cloned the latest master but somehow ran into a series of problems when running the demo command. Could you please have a try on `hatch run train` and check if everything works fine? The repo works normally after editing below. Please let me know if you need reproduction of errors.

### CODE REVIEW

**Comment by Michedev** [comment]
Thank you for the interest! I will check the code on this afternoon

**Comment by botbw** [comment]
> Thank you for the interest! I will check the code on this afternoon

Hi, those commits are just simple hacks to run the code. 

Most of the errors are due to library API deprecation. Could you please check if the dependencies config for `hatch` are consistent with the repo?

**Comment by Michedev** [comment]
Thanks for the contribution! I have only one question: why did you add this check in the `predict(x)` method? 

        if isinstance(x, list):
            x = x[0]

**Comment by botbw** [comment]
> Thanks for the contribution! I have only one question: why did you add this check in the `predict(x)` method?
> 
> ```
>     if isinstance(x, list):
>         x = x[0]
> ```

Cuz I found `x` is `list` during training but is `tensor` during test (didn't dig to find the causes), again this might not be the correct impl but it worked for me :)

And thanks for the repo, it really helps reduce my work!

**Comment by Michedev** [comment]
Can I ask for what do you use the repo? Just for curiosity.

Can you provide me the test code? Because I checked the codebase and it doesn't make sense that there is a list over there.

**Comment by botbw** [comment]
> Can I ask for what do you use the repo? Just for curiosity.
> 
> Can you provide me the test code? Because I checked the codebase and it doesn't make sense that there is a list over there.

Haha, I was trying to perform a one-class classification task (e.g. class "A" and "not A"), trained the VAE with "A" data then tried to find a threshold to separate the distributions of "A" and "not A". It outperforms the binary classifier in the aspect of generalization! (in my situation, test data mostly doesn't appear in the trainset).

And by the word "test", I actually meant to say "validation" (To be more clear I got the error after the training epoch). But I'm using a custom dataset so I guess it should be all right if you manage to run it locally on MNIST?

I wrote my own test code and it's basically
```python
    test_p = []
    for batch in test_loader: # batch is (data,) no labeling
        test_p.append(model.reconstructed_probability(batch[0]))
    test_p = torch.cat(test_p)
```

**Pull request closed without merging**
